.TH play.it 6 2018-05-15
.SH NAME
\[char46]/play.it \- Installer for drm-free commercial games
.SH SYNOPSIS
.B play.it
.I installer
.SH DESCRIPTION
.I installer
must be a supported game installation file (.exe, .sh, ...) at a known version
.PP
.B play.it
repackages the game data and engine from the provided
.I installer
into a .deb or .pkg and displays the command needed to install the game.
.PP
The games are installed globally on multi-user systems, avoiding unnecessary
duplication. The locations of save games, settings, mods, temporary files and
backups are standardized with XDG Base Directory support.
.SH ENVIRONMENT
.I PLAYIT_LIB2
If set, overrides the provided version of
.B libplayit.sh
(and its supported games) to a local copy for development
(default: /usr/share/games/play.it/libplayit2.sh)
